### ISSUE TITLE
Missing profile photos

### ISSUE THREAD

**Issue by asood123** [OpenCollective/opencollective-website#108]
Let's figure out a way to tackle our missing avatars. This looks terrible: https://opencollectiveinc.slack.com/files/piamancini/F0UHK1GGJ/slack_for_ios_upload.jpg. And it's been on our list for several weeks.

Goal: How do we increase the number of profile photos on the site? 

Some things to consider:
- What flow makes most sense to encourage users to add their own avatars?
  1. Add it post-donation
  2. Add it to the subscription page
  3. Make it a clickable link on a public page (ex: hovering over an avatar on public page asks you to upload a photo via email verification. "Is this you? Upload your photo. Takes you to My subscription after email verification and lets you upload a photo)
- Can we do it manually somehow? 
- Could we add something in the donation confirmation email?
- Should we change UI to reduce the size while we increase the number?

@xdamman @piamancini @arnaudbenard @sedubois

**Comment by GranularDetective** [comment]
You can use the same gravatar for two images, xdamman.
