### ISSUE TITLE
Connect Twitter Account

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/opencollective-website#111]
We should have a way to connect a Twitter account to a collective. This will enable us to: 
- publicly acknowledge and welcome new backers: *"@xdamman thanks for backing us!"*
- send a monthly tweet to thanks the sponsors: *"We would like to thanks our sponsors @gitlab, @yahoo and @skycatch. Become a sponsor: https://OpenCollective.com/RailsGirlsAtl/sponsors"*

For now, we don't need to worry too much about the UX. We just need a way to connect the Twitter account.

We should have page `/:collective/connect/:service`, e.g. https://opencollective.com/RailsGirlsAtl/connect/twitter with a button "Connect your Twitter account". This should create a new row in the `ConnectedAccounts` table with a link to the `GroupId` of the collective.

Then at the API level, we should have an easy to use function to send a tweet on behalf of a collective.

**Comment by xdamman** [comment]
I would also add Github to help with https://github.com/OpenCollective/OpenCollective/issues/33

**Comment by sedubois** [comment]
Github ongoing in 
https://github.com/OpenCollective/api/pull/324
https://github.com/OpenCollective/website/pull/204

**Comment by GranularDetective** [comment]
You should probably use Vorpal.js and do all the twitter stuff via the command line. Vorpal.js is epic.

**Comment by sedubois** [comment]
Tweeting done in https://github.com/OpenCollective/opencollective-api/pull/450
Still to-do monthly thanking of sponsors in separate PR
