### ISSUE TITLE
Top menu not working on subpages

### ISSUE THREAD

**Issue by ondrae** [OpenCollective/opencollective-website#140]
The top menu isn't working when on the /faq or /about pages.

You end up with urls like https://opencollective.com/faq#how and https://opencollective.com/about#usecases.

Good luck with the new site though!

**Comment by carlosascari** [comment]
Closing, as this issue was fixed during the Mobile version of the `LoginTopBar` PR 
https://github.com/OpenCollective/opencollective-website/pull/366/files
