### ISSUE TITLE
Logo in footer not vertically centered

### ISSUE THREAD

**Issue by dasilvacontin** [OpenCollective/opencollective-website#167]
<img width="283" alt="screenshot 2016-04-18 21 39 41" src="https://cloud.githubusercontent.com/assets/1260830/14617341/2531ed02-05ae-11e6-9e29-c8bcf1598823.png">

**Comment by GranularDetective** [comment]
Set margin:auto on this.

**Comment by carlosascari** [comment]
Closing as the logo was vertically aligned in the [Responsive Footer PR](https://github.com/OpenCollective/opencollective-website/pull/394#issue-170274670)

**Comment by GranularDetective** [comment]
Fascinating.

Sent from Yahoo Mail on Android 
 
  On Thu, 18 Aug, 2016 at 19:13, Ascari<notifications@github.com> wrote:   
Closing as the logo was vertically aligned in the Responsive Footer PR
