### ISSUE TITLE
Extra curly brace

### ISSUE THREAD

**Issue by samhatoum** [OpenCollective/opencollective-website#239]
Check it:

![](https://gmkr.io/s/573b4a78ec1a57e50b66df7c/0)

**Comment by asood123** [comment]
Very observant, @samhatoum ;-). We should have you look over more stuff!

Thanks for reporting.

**Comment by samhatoum** [comment]
We are in the business of testing after all :)

**Comment by sedubois** [comment]
Fixed by https://github.com/OpenCollective/opencollective-website/pull/241
