### ISSUE TITLE
Fix 'Join us...' color 

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/opencollective-website#251]
In https://opencollective.com/vcr#support the text 'Join us and help us fulfill our mission' is in white 
see screenshot 
<img width="1119" alt="screen shot 2016-05-19 at 7 45 23 am" src="https://cloud.githubusercontent.com/assets/3671070/15397682/eab72a2a-1d95-11e6-8555-5fed2537193d.png">

**Comment by asood123** [comment]
Is that happening in other collectives too?

**Comment by piamancini** [comment]
yes

**Comment by carlosascari** [comment]
PR w/fix sent

**Comment by piamancini** [comment]
was this pushed? I'm still seeing it in white, but don't see the PR w fix.

**Comment by asood123** [comment]
I don't think so. We'll push tmrw

**Comment by carlosascari** [comment]
Issue resolved
