### ISSUE TITLE
Wrong links on Webpack home page

### ISSUE THREAD

**Issue by visualpharm** [OpenCollective/opencollective-website#697]
The last links are wrong at the moment at [Webpack](https://webpack.js.org/)

![image](https://cloud.githubusercontent.com/assets/5383670/24582148/dd3a0e12-16ff-11e7-900e-eac3ee7ae841.png)

Maybe it's temporary however, until the caches/generators refresh the content.

**Comment by asood123** [comment]
most likely cache issue. Let's wait for an hour and see.

**Comment by visualpharm** [comment]
You're right! And I appreciate your fast response.
