### ISSUE TITLE
Login flow is a bit weird

### ISSUE THREAD

**Issue by yeskunall** [opencollective/opencollective-website#764]
Hey guys 👋

I was reading @piamancini's [article](https://medium.com/open-collective/open-collective-v2-is-live-61b7cd3195e3) (congratulations on v2 of @opencollective, btw 😍) and decided it was finally time to create an account. That's when I realized that the login/sign up flow is a bit... weird. I say weird because UX is a very hard thing and it's impossible to live up to every end-users' expectations. With that being said, I want you guys to know that the following is just my feedback, and nothing more.

* The login page (currently) does not have a set `title`. Was this intentional? 🤔
* The flow from clicking on login to landing on the page works fine, but then I'm greeted with this screen:

![image](https://user-images.githubusercontent.com/14703164/31297789-66ea5cf4-aab5-11e7-938d-d84f1833c272.png)

... which to me, as an end-user, is a bit lacking. As a new user, what do I do? The __intent__ &mdash; that typing in a valid email address brings up a whole array of options (fields, in this case) &mdash; is less than clear. Maybe this could be worked on a bit more?

Now I'm going to go ahead and sign up for an account! Cheers! ❤️ 

**UPDATE**

Just finished the sign up process. Once again I feel like the whole flow lacks feedback.

![image](https://user-images.githubusercontent.com/14703164/31298296-899fdede-aab7-11e7-8b87-9be81e4049b0.png)

I like the whole idea of "one-click login" via email, but once again in this case I feel like the login process could be improved a bit.

**Comment by xdamman** [comment]
Thanks for the feedback!
This definitely needs some more work. I'm adding a title right now :-)
@cuiki can you come up with some ideas to improve this?

There are multiple situations here that we are trying to handle that doesn't make this easy:
- Existing users just want to enter their email and be done (so not a fan of showing all the fields by default)
- We wanted to offer a password free experience (while that sounded like a great idea, I'm less and less convinced. Mostly by the fact that people are so used to deal with password, that they are surprised and not used not to have a password.)

One way we could make this simpler is to separate the flows. This could only be the flow to sign in. And to sign up, we could require people to make a first donation. It would also make sure that their new profile is not empty.

Alright, food for thoughts. It's late so crashing here in Brussels.
Thanks again for your feedback! Work in progress!
