### ISSUE TITLE
It's not possible to remove a cover image

### ISSUE THREAD

**Issue by elopio** [opencollective/opencollective-website#783]
I made the wrong selection for the cover image, because as explained in https://github.com/opencollective/opencollective/issues/779, it looks back with the black text.

The problem now is that there is no way to remove the cover image. So I'm forced to find a new one that is more white. I should be able to undo everything I do, so I should be able to remove the cover image and go back to plain white background.

**Comment by piamancini** [comment]
closing this in favour or https://github.com/opencollective/opencollective/issues/1067
