### ISSUE TITLE
Text Editor on Updates not working?

### ISSUE THREAD

**Issue by amykirschner** [opencollective/opencollective-website#788]
Using the Update feature. 

Used bullet points but even after saving, they are not visible.

https://opencollective.com/oscurrency/updates/21418-update-ruby-upgrade-demo-on-deck#updates

**Comment by piamancini** [comment]
hi @amykirschner yes, I can reproduce it. There seems to be a bug. I'll report it https://github.com/opencollective/opencollective/issues/911

**Comment by amykirschner** [comment]
@piamancini thank you!
