### ISSUE TITLE
Sponsor's avatar and website aren't match

### ISSUE THREAD

**Issue by outsideris** [opencollective/opencollective-website#793]
In [mocha](https://opencollective.com/mochajs), avatar image and the website aren't match.
For instance, https://opencollective.com/mochajs/sponsor/5/avatar.svg is Yahoo and https://opencollective.com/mochajs/sponsor/5/website is dontpayfull.

See, https://github.com/mochajs/mocha/issues/3297 .

**Comment by piamancini** [comment]
I'm seeing both avatar and website for dontpayfull

**Comment by outsideris** [comment]
@piamancini hmm..
I'm using chrome, but it is fine now for me as well.
